-- migrate:up
ALTER TABLE match_timelines
  ADD COLUMN blue_top_cs INTEGER DEFAULT 0,
  ADD COLUMN blue_top_level INTEGER DEFAULT 1,
  ADD COLUMN blue_top_kills INTEGER DEFAULT 0,
  ADD COLUMN blue_jg_cs INTEGER DEFAULT 0,
  ADD COLUMN blue_jg_level INTEGER DEFAULT 1,
  ADD COLUMN blue_jg_kills INTEGER DEFAULT 0,
  ADD COLUMN blue_mid_cs INTEGER DEFAULT 0,
  ADD COLUMN blue_mid_level INTEGER DEFAULT 1,
  ADD COLUMN blue_mid_kills INTEGER DEFAULT 0,
  ADD COLUMN blue_bot_cs INTEGER DEFAULT 0,
  ADD COLUMN blue_bot_level INTEGER DEFAULT 1,
  ADD COLUMN blue_bot_kills INTEGER DEFAULT 0,
  ADD COLUMN blue_sup_cs INTEGER DEFAULT 0,
  ADD COLUMN blue_sup_level INTEGER DEFAULT 1,
  ADD COLUMN blue_sup_kills INTEGER DEFAULT 0,
  ADD COLUMN red_top_cs INTEGER DEFAULT 0,
  ADD COLUMN red_top_level INTEGER DEFAULT 1,
  ADD COLUMN red_top_kills INTEGER DEFAULT 0,
  ADD COLUMN red_jg_cs INTEGER DEFAULT 0,
  ADD COLUMN red_jg_level INTEGER DEFAULT 1,
  ADD COLUMN red_jg_kills INTEGER DEFAULT 0,
  ADD COLUMN red_mid_cs INTEGER DEFAULT 0,
  ADD COLUMN red_mid_level INTEGER DEFAULT 1,
  ADD COLUMN red_mid_kills INTEGER DEFAULT 0,
  ADD COLUMN red_bot_cs INTEGER DEFAULT 0,
  ADD COLUMN red_bot_level INTEGER DEFAULT 1,
  ADD COLUMN red_bot_kills INTEGER DEFAULT 0,
  ADD COLUMN red_sup_cs INTEGER DEFAULT 0,
  ADD COLUMN red_sup_level INTEGER DEFAULT 1,
  ADD COLUMN red_sup_kills INTEGER DEFAULT 0;

TRUNCATE match_timelines;

-- migrate:down
ALTER TABLE match_timelines
  DROP COLUMN IF EXISTS blue_top_cs,
  DROP COLUMN IF EXISTS blue_top_level,
  DROP COLUMN IF EXISTS blue_top_kills,
  DROP COLUMN IF EXISTS blue_jg_cs,
  DROP COLUMN IF EXISTS blue_jg_level,
  DROP COLUMN IF EXISTS blue_jg_kills,
  DROP COLUMN IF EXISTS blue_mid_cs,
  DROP COLUMN IF EXISTS blue_mid_level,
  DROP COLUMN IF EXISTS blue_mid_kills,
  DROP COLUMN IF EXISTS blue_bot_cs,
  DROP COLUMN IF EXISTS blue_bot_level,
  DROP COLUMN IF EXISTS blue_bot_kills,
  DROP COLUMN IF EXISTS blue_sup_cs,
  DROP COLUMN IF EXISTS blue_sup_level,
  DROP COLUMN IF EXISTS blue_sup_kills,
  DROP COLUMN IF EXISTS red_top_cs,
  DROP COLUMN IF EXISTS red_top_level,
  DROP COLUMN IF EXISTS red_top_kills,
  DROP COLUMN IF EXISTS red_jg_cs,
  DROP COLUMN IF EXISTS red_jg_level,
  DROP COLUMN IF EXISTS red_jg_kills,
  DROP COLUMN IF EXISTS red_mid_cs,
  DROP COLUMN IF EXISTS red_mid_level,
  DROP COLUMN IF EXISTS red_mid_kills,
  DROP COLUMN IF EXISTS red_bot_cs,
  DROP COLUMN IF EXISTS red_bot_level,
  DROP COLUMN IF EXISTS red_bot_kills,
  DROP COLUMN IF EXISTS red_sup_cs,
  DROP COLUMN IF EXISTS red_sup_level,
  DROP COLUMN IF EXISTS red_sup_kills;
